---
title: "R Notebook"
output: html_notebook
---

Work on problem two!



#problem 1

```{r}
daily_activity <- read_csv("dailyActivity_merged.csv", trim_ws = TRUE, show_col_types = FALSE)
glimpse(daily_activity)
n_distinct(daily_activity$Id)

summary(daily_activity)
```






```{r}
filter(daily_activity, TotalSteps != 0)
```
```{r}
df<-
  filter(daily_activity, TotalSteps == 0) %>% 
  select(Id, ActivityDate) %>% 
  rename(activity_date = ActivityDate,
         id= Id) %>% 
  mutate(id = as.character(id)) %>% 
  mutate( activity_date = as.Date(activity_date, 
                                  format = "%m/%d/%Y")) %>% 
  mutate(time= 0,
         calories=0,
         total_intensity=0,
         average_intensity=0,
         step_total=0) %>% 
  mutate(time=as.character(time))




          
df                     
```

```{r}
df1<-
  filter(daily_activity, TotalSteps == 0) %>% 
  select(Id, ActivityDate) %>% 
  rename(activity_date = ActivityDate,
         id= Id) %>% 
  mutate(id = as.character(id)) %>% 
  mutate( activity_date = as.Date(activity_date, 
                                  format = "%m/%d/%Y"))

df1
```





```{r}
glimpse(df)
```


```{r}
select(filter(daily_activity, TotalSteps == 0), Id, ActivityDate)

```

#problem 2
```{r}
hourly_calories <- read_csv("hourlyCalories_merged.csv", trim_ws = TRUE, show_col_types = FALSE) 
hourly_intensities <- read_csv("hourlyIntensities_merged.csv", trim_ws = TRUE, show_col_types = FALSE) 
hourly_steps <- read_csv("hourlySteps_merged.csv", trim_ws = TRUE, show_col_types = FALSE) 
```

```{r}
#Join the hourly data sets (hourly_calories, hourly_intensities, hourly_steps)

hourly_activity <- inner_join(hourly_calories, hourly_intensities, by = c("Id","ActivityHour"))

hourly_activity <-inner_join(hourly_activity, hourly_steps, by = c("Id","ActivityHour"))
```

```{r}
# Check hourly_activity data set before cleaning 
glimpse(hourly_activity) 

#Check missing values and duplicates
cat("\n",
    "Missing values:", sum(is.na(hourly_activity)),
    "\n",
    "Duplicate values:", sum(duplicated(hourly_activity))
)
```



```{r}
# Clean hourly_activity data set

#Clean column names
hourly_activity <- clean_names(hourly_activity) %>% 
  #Correct column types   
  mutate(id = as.character(id)) %>%  #From double to chr
  mutate( activity_hour = as_datetime(activity_hour,
                                   format ="%m/%d/%Y %I:%M:%S %p"))%>%  #From chr to datetime
  #Remove duplicate rows
  distinct()

#Check clean daily_activity data set
glimpse(hourly_activity)


#Check missing values and duplicates after cleaning
cat("\n",
    "Missing values:", sum(is.na(hourly_activity)),
    "\n",
    "Duplicate values:", sum(duplicated(hourly_activity))
    )

#as_datetime() converts with default timezone = "UTC"
```

```{r}
df_try<-hourly_activity
dim(df_try)
head(df_try)
```





```{r}
df_try<-df_try %>% 
  separate(activity_hour , into = c('activity_date', 'time'), sep=' ') %>% 
  mutate( activity_date = as.Date(activity_date))

df_try 
```
```{r}
df_last<-  anti_join(df_try, df, by = c("id","activity_date") )


```

```{r}
df_last
```


```{r}
df_last %>% 
  group_by(id,activity_date) %>% 
  summarise(total_steps = sum(step_total)) 
  #filter(total_steps !=0)
  


```



```{r}
df1<-
  filter(daily_activity, TotalSteps != 0) %>% 
  select(Id, ActivityDate) %>% 
  rename(activity_date = ActivityDate,
         id= Id) %>% 
  mutate(id = as.character(id)) %>% 
  mutate( activity_date = as.Date(activity_date, 
                                  format = "%m/%d/%Y"))

df1
```
```{r}
df_try
```



```{r}

 another<-inner_join(df_try, df1, by = c("id","activity_date")) 
 another

```

```{r}
data<-inner_join(df_try, df1, by = c("id","activity_date"))%>% 
  group_by(id,activity_date) %>% 
  summarise(total_steps = sum(step_total))
```
```{r}
data2<-filter(daily_activity, TotalSteps != 0)
```

```{r}
y<-data$total_steps
```

```{r}
length(x)
length(y)

```
```{r}
setdiff(x,y)

```






```{r}
p<-setdiff(z,w)
p
```


```{r}
 #declaring first integer vector
vec1 <- c(1, 3, 5, 4, 2)
  
# declaring second string vector
vec2 <- c(4, 5, 6, 7, 8)
  
print ("Original vector1 ")
print (vec1)
  
print ("Original vector2 ")
print (vec2)
  
# computing the difference 
# in vectors
diff <- setdiff(vec1,vec2)
print ("Vec1- Vec2")
print (diff)
```
```{r}
typeof(vec2)
```
```{r}

df2<-
  filter(daily_activity, TotalSteps == 0) %>% 
  select(Id, ActivityDate) %>% 
  rename(activity_date = ActivityDate,
         id= Id) %>% 
  mutate(id = as.character(id)) %>% 
  mutate( activity_date = as.Date(activity_date, 
                                  format = "%m/%d/%Y"))

df2
```
```{r}
df_bad<-inner_join(df_try, df2, by = c("id","activity_date"))%>% 
  group_by(id,activity_date) %>%  
  summarise(total_steps = sum(step_total))

df_bad

```
```{r}
data %>%
  ggplot( aes(x=total_steps)) +
  geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.5) 
  #geom_histogram()
```


```{r}
data2 %>%
  ggplot( aes(x=TotalSteps)) +
  geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.5) 
```



